name: next_check
description: "A new Flutter project for next venture."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  latlong2: ^0.9.1
  geolocator: ^14.0.1
  google_maps_flutter: ^2.10.1
  ntp: ^2.0.0
  zoom_tap_animation: ^1.1.0
  get_storage: ^2.1.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.1
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^19.2.1
  cloud_firestore: ^5.6.4
  lottie: ^3.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

  # flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/
    - assets/logo/


  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/nextcheck.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/nextcheck.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/nextcheck.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/nextcheck.png"

