// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdvZ_rqlaI633iErq_bEpbUTvX41U-8FE',
    appId: '1:334034605461:web:a4d64e6e5f6be61224529c',
    messagingSenderId: '334034605461',
    projectId: 'nexcheck-165b8',
    authDomain: 'nexcheck-165b8.firebaseapp.com',
    storageBucket: 'nexcheck-165b8.firebasestorage.app',
    measurementId: 'G-5T1XCB2Y8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDUr_3rkWnWTDK3iUafYC6U2wwSyjHO4',
    appId: '1:334034605461:android:dcb0f8dac1de676624529c',
    messagingSenderId: '334034605461',
    projectId: 'nexcheck-165b8',
    storageBucket: 'nexcheck-165b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaMke5GNy49cCgtrQyTTBL68gI3EBKrE',
    appId: '1:334034605461:ios:04be57438e72655124529c',
    messagingSenderId: '334034605461',
    projectId: 'nexcheck-165b8',
    storageBucket: 'nexcheck-165b8.firebasestorage.app',
    iosBundleId: 'com.example.nextCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaMke5GNy49cCgtrQyTTBL68gI3EBKrE',
    appId: '1:334034605461:ios:04be57438e72655124529c',
    messagingSenderId: '334034605461',
    projectId: 'nexcheck-165b8',
    storageBucket: 'nexcheck-165b8.firebasestorage.app',
    iosBundleId: 'com.example.nextCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdvZ_rqlaI633iErq_bEpbUTvX41U-8FE',
    appId: '1:334034605461:web:eb2568ac8e4b305b24529c',
    messagingSenderId: '334034605461',
    projectId: 'nexcheck-165b8',
    authDomain: 'nexcheck-165b8.firebaseapp.com',
    storageBucket: 'nexcheck-165b8.firebasestorage.app',
    measurementId: 'G-5G2RC1F598',
  );
}
